### ISSUE TITLE
ActivityNet dataset size

### ISSUE THREAD

**Issue by stha-prashant** [mxingzhang90/MSAT#3]
When I run the training script on activitynet, the number of iterations for train is less than for val and test, is this supposed to happen?  This image is for batch size 58 and the iterations for train, test and val respectively.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/43800155/220004647-1168ca4c-0996-46e0-a745-306ed1353686.png">

**Comment by mxingzhang90** [comment]
Have you changed the batch size of testing stage?

**Comment by stha-prashant** [comment]
Yes, for both I've set it to 58. I've found the problem, apparently the test interval is set to 0.25, so I was mistaken in thinking that one progress bar completion meant an epoch completion. Thank you.
